# Generated by Django 4.2 on 2023-04-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_added',
        ),
    ]
