# Generated by Django 4.2 on 2023-04-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0005_remove_comment_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='beitrag',
        ),
    ]
