# Generated by Django 4.2 on 2023-04-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0007_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
